server:
  port: 8000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka

spring:
  application:
    name: api-gateway-service

  security:
    oauth2:
      client:
        registration:                                                       # client setting
          keycloak:                                                         # oidc-client
            provider: keycloak
            client-id: account
            client-secret: p1ptVEsG0iQZ5ofNFojaLoTzVFjkSk2y
            redirectUri: http://localhost:8000/login/oauth2/code/keycloak
            authorization-grant-type: authorization_code
            scope: openid, profile, email, roles

        provider:                                                           # provider setting
          keycloak:                                                         # oidc-provider
            issuer-uri: http://0.0.0.0:8080/realms/variety-store

      resourceserver:
        jwt:
          issuer-uri: http://0.0.0.0:8080/realms/variety-store

logging:
  level:
    root: INFO